"""Extract the translatable strings into a per-language catalog.

The knowledge graph is language-neutral: ids, types, relations, sources, phases,
categories' structure — none of it is ever translated. Only *display text* is:
per atom (title, aliases, and the renditions) and per category (title, summary).

This tool writes the SOURCE catalog (``i18n/en/catalog.en.json``) — a stable,
diff-able list of exactly those strings. Softly's DeepL pipeline consumes it and
produces the same shape for each target language at ``i18n/<lang>/catalog.<lang>.json``.
A later build step overlays those catalogs into the ``*_text`` tables per language.

    python3 -m pipeline.i18n_extract            # writes i18n/en/catalog.en.json

The file is GENERATED — do not hand-edit it; edit the Markdown atoms and re-run.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from .compile_sqlite import _BODY_FIELDS, _content_checksum
from .loader import SOURCE_LANG, load_corpus

REPO_ROOT = Path(__file__).resolve().parent.parent

# Order the fields the way a translator reads them; keep nulls so the target
# catalog has every slot and DeepL never has to guess the shape.
_ATOM_FIELDS = ("title", "aliases") + _BODY_FIELDS


def build_catalog(content_dir: Path, categories_file: Path, paths_file: Path,
                  lang: str) -> dict:
    corpus = load_corpus(content_dir, categories_file, paths_file, lang)
    published = sorted(
        (a for a in corpus.atoms if a.status == "published"), key=lambda a: a.id
    )

    atoms = {}
    for atom in published:
        fm = atom.frontmatter
        r = atom.renditions
        atoms[atom.id] = {
            "title": fm["title"],
            "aliases": fm.get("aliases") or [],
            "glance": r.get("glance"),
            "overview": r.get("overview"),
            "deep": r.get("deep"),
            "when_to_see_doctor": r.get("when_to_see_doctor"),
            "red_flags": r.get("red_flags"),
        }

    categories = {
        c.id: {"title": c.title, "summary": c.summary}
        for c in sorted(corpus.categories, key=lambda c: (c.order, c.id))
    }

    paths = {
        p.id: {"title": p.title, "summary": p.summary}
        for p in sorted(
            (p for p in corpus.paths if p.status == "published"),
            key=lambda p: (p.order, p.id),
        )
    }

    return {
        "_meta": {
            "lang": lang,
            "is_source": lang == SOURCE_LANG,
            "source_content_checksum": _content_checksum(
                published, corpus.categories_checksum, corpus.paths_checksum
            ),
            "note": "GENERATED by pipeline.i18n_extract — do not hand-edit.",
            "translatable_atom_fields": list(_ATOM_FIELDS),
            "never_translate": ["id", "type", "category", "relations", "sources",
                                "phases", "illustrationId", "review", "status",
                                "order", "steps"],
        },
        "atoms": atoms,
        "categories": categories,
        "paths": paths,
    }


def _parse_args(argv):
    p = argparse.ArgumentParser(
        prog="pipeline.i18n_extract",
        description="Extract translatable strings into i18n/<lang>/catalog.<lang>.json",
    )
    p.add_argument("--content", type=Path, default=REPO_ROOT / "content" / "en")
    p.add_argument("--categories", type=Path,
                   default=REPO_ROOT / "categories" / "categories.yaml")
    p.add_argument("--paths", type=Path,
                   default=REPO_ROOT / "paths" / "paths.yaml")
    p.add_argument("--lang", default=SOURCE_LANG,
                   help="catalog language code (default: en, the source)")
    p.add_argument("--out", type=Path, default=None,
                   help="output path (default: i18n/<lang>/catalog.<lang>.json)")
    return p.parse_args(argv)


def main(argv=None) -> int:
    args = _parse_args(argv)
    catalog = build_catalog(args.content, args.categories, args.paths, args.lang)
    out = args.out or REPO_ROOT / "i18n" / args.lang / f"catalog.{args.lang}.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        json.dumps(catalog, ensure_ascii=False, indent=2, sort_keys=False) + "\n",
        encoding="utf-8",
    )
    print(f"✓ extracted {len(catalog['atoms'])} atom(s) + "
          f"{len(catalog['categories'])} categories + {len(catalog['paths'])} path(s) "
          f"→ {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
